import { useContext, useState } from "react";
import { TaskContext } from "../context/TaskContext";
import { updateTask } from "../services/taskService";
import { generateTaskBreakdown } from "../services/geminiService";

export default function AIPlanner() {
  
  const { tasks, setTasks } = useContext(TaskContext);
  const [selectedTaskId, setSelectedTaskId] = useState("");
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");



  const [plan, setPlan] = useState("");
  const [loading, setLoading] = useState(false);

  
const handleGenerate = async () => {
  setError("");
setSuccess("");
  if (!selectedTaskId) {
    setError("Please select a task first.");
    return;
  }

  setLoading(true);

  try {
    const task = tasks.find(
      (t) => t.id === selectedTaskId
    );

    

    const result = await generateTaskBreakdown(task);

    const subtasks = result
  .split("\n")
  .filter((line) => line.trim() !== "")
  .map((line) => ({
    title: line.replace(/^\d+\.\s*/, "").trim(),
    completed: false,
  }));

   await updateTask(task.id, {
  aiRecommendation: result,
  subtasks,
});

   setTasks(
  tasks.map((t) =>
    t.id === task.id
      ? {
          ...t,
          aiRecommendation: result,
          subtasks,
        }
      : t
  )
);
  setPlan(result);
   setSuccess("AI task breakdown generated successfully!");
  } catch (error) {
    console.error(error);
    setError("Failed to generate AI breakdown. Please try again.");
  }

  setLoading(false);
};

  return (
    <div className="min-h-screen bg-slate-100 p-4 md:p-8">
      <div className="max-w-3xl w-full mx-auto bg-white shadow-xl rounded-3xl p-8">
        <h1 className="text-3xl font-bold mb-2">
  🤖 Guardian AI
</h1>

<p className="text-gray-500 mb-6">
  Your intelligent productivity assistant
</p>

     <select
  value={selectedTaskId}
  onChange={(e) =>
    setSelectedTaskId(e.target.value)
  }
  className="w-full border p-3 rounded-xl mb-4"
>
  <option value="">
    Select a Task
  </option>

  {tasks.map((task) => (
    <option
      key={task.id}
      value={task.id}
    >
      {task.title}
    </option>
  ))}
</select>
Above your button

Add:

{error && (
  <div className="mb-4 bg-red-100 border border-red-300 text-red-700 p-4 rounded-xl">
    ❌ {error}
  </div>
)}

{success && (
  <div className="mb-4 bg-green-100 border border-green-300 text-green-700 p-4 rounded-xl">
    ✅ {success}
  </div>
)}

       <button
  onClick={handleGenerate}
  disabled={loading}
  className={`flex items-center justify-center gap-3 px-6 py-3 rounded-xl text-white font-semibold transition ${
    loading
      ? "bg-gray-400 cursor-not-allowed"
      : "bg-purple-600 hover:bg-purple-700"
  }`}
>
  {loading && (
    <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
  )}

  {loading
    ? "Guardian AI is thinking..."
    : "✨ Generate Task Breakdown"}
</button>

{loading && (
  <div className="mt-6 bg-purple-50 border border-purple-200 rounded-2xl p-5">
    <p className="text-purple-700 font-medium">
      🤖 Guardian AI is analyzing your task...
    </p>

    <p className="text-sm text-gray-500 mt-2">
      Breaking your task into actionable subtasks.
    </p>
  </div>
)}

<div className="flex items-center gap-2 mb-4">
  <div className="w-3 h-3 rounded-full bg-green-500"></div>

  <p className="font-semibold text-purple-700">
    Generated by Gemini AI
  </p>
</div>

        {plan && (
          <div className="mt-8 bg-slate-50 p-6 rounded-2xl">
            <h2 className="font-bold mb-3">
              🧩 AI Task Breakdown
            </h2>

            <div className="bg-gradient-to-r from-purple-50 to-pink-50 p-6 rounded-2xl shadow-md border border-purple-100">
  <div className="whitespace-pre-wrap text-left leading-7">
    {plan}
  </div>
</div>
          </div>
        )}
      </div>
    </div>
  );
}