import { useContext, useState } from "react";
import { TaskContext } from "../context/TaskContext";
import { generateReschedule } from "../services/geminiService";

export default function Rescheduler() {
  const { tasks } = useContext(TaskContext);

  const [schedule, setSchedule] = useState("");
  const [loading, setLoading] = useState(false);

  const [error, setError] = useState("");
const [success, setSuccess] = useState("");

  const handleGenerate = async () => {

    setError("");
setSuccess("");
    if (tasks.length === 0) {
      setError("Please select a task first.");
return;
    }

    setLoading(true);

    try {
      const result = await generateReschedule(tasks);
      setSchedule(result);
      setSuccess("AI task rescheduled successfully!");
    } catch (error) {
      console.error(error);
      setSchedule("");
      setError("Failed to reschdule the tasks. Please try again.");
    }

    setLoading(false);
  };

  return (
    <div className="min-h-screen bg-slate-100 p-4 md:p-8">
      <div className="max-w-4xl w-full mx-auto bg-white rounded-3xl shadow-xl p-4 md:p-8">

        <h1 className="text-3xl font-bold">
          🔄 AI Task Rescheduler
        </h1>

        <p className="text-gray-500 mt-2 mb-6">
          Let Guardian AI reorganize your remaining tasks.
        </p>

        {error && (
  <div className="mb-4 bg-red-100 border border-red-300 text-red-700 p-4 rounded-xl">
    ❌ {error}
  </div>
)}

{success && (
  <div className="mb-4 bg-green-100 border border-green-300 text-green-700 p-4 rounded-xl">
    ✅ {success}
  </div>
)}

      <button
  onClick={handleGenerate}
  disabled={loading}
  className={`flex items-center justify-center gap-3 px-6 py-3 rounded-xl text-white font-semibold transition ${
    loading
      ? "bg-gray-400 cursor-not-allowed"
      : "bg-purple-600 hover:bg-purple-700"
  }`}
>
  {loading && (
    <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
  )}

  {loading
    ? "Guardian AI is rescheduling..."
    : "✨ AI Reschedule"}
</button>
{loading && (
  <div className="mt-6 bg-purple-50 border border-purple-200 rounded-2xl p-5">
    <p className="text-purple-700 font-semibold">
      🔄 Guardian AI is optimizing your schedule...
    </p>

    <p className="text-gray-500 mt-2">
      Finding the best order to finish your tasks before their deadlines.
    </p>
  </div>
)}

<div className="flex items-center gap-2 mb-4">
  <div className="w-3 h-3 rounded-full bg-green-500"></div>

  <p className="font-semibold text-purple-700">
    Generated by Gemini AI
  </p>
</div>

        {schedule && (
          <div className="mt-8 bg-gradient-to-r from-purple-50 to-pink-50 p-6 rounded-2xl whitespace-pre-wrap">
            {schedule}
          </div>
        )}

      </div>
    </div>
  );
}