import { useContext, useState } from "react";
import { TaskContext } from "../context/TaskContext";
import { generateDailyPlan } from "../services/geminiService";

export default function DailyPlanner() {
  const { tasks } = useContext(TaskContext);

  const [plan, setPlan] = useState("");
  const [loading, setLoading] = useState(false);

  const [error, setError] = useState("");
const [success, setSuccess] = useState("");

  const handleGenerate = async () => {
    setError("");
setSuccess("");
  if (tasks.length === 0) {
   setError("No tasks available to plan.");
    return;
  }

  setLoading(true);

  try {
    const result = await generateDailyPlan(tasks);
    setPlan(result);
    setSuccess("Today's schedule generated successfully!");
  } catch (error) {
    console.error(error);
    setError("Unable to generate today's schedule.");
  }

  setLoading(false);
};

  return (
    <div className="bg-white rounded-3xl shadow-lg p-6 mb-8">
      <h2 className="text-2xl font-bold mb-2">
        🎯 AI Daily Planner
      </h2>

      <p className="text-gray-500 mb-5">
        Let AI organize your day based on priorities.
      </p>

      {error && (
  <div className="mb-4 bg-red-100 border border-red-300 text-red-700 p-4 rounded-xl">
    ❌ {error}
  </div>
)}

{success && (
  <div className="mb-4 bg-green-100 border border-green-300 text-green-700 p-4 rounded-xl">
    ✅ {success}
  </div>
)}
<button
  onClick={handleGenerate}
  disabled={loading}
  className={`flex items-center justify-center gap-3 px-6 py-3 rounded-xl text-white font-semibold transition ${
    loading
      ? "bg-gray-400 cursor-not-allowed"
      : "bg-purple-600 hover:bg-purple-700"
  }`}
>
  {loading && (
    <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
  )}

  {loading
    ? "Guardian AI is planning your day..."
    : "✨ Generate Today's Plan"}
</button>
{loading && (
  <div className="mt-6 bg-purple-50 border border-purple-200 rounded-2xl p-5">
    <p className="text-purple-700 font-semibold">
      📅 Guardian AI is creating your schedule...
    </p>

    <p className="text-gray-500 mt-2">
      Prioritizing tasks, checking deadlines and estimating today's workload.
    </p>
  </div>
)}

<div className="flex items-center gap-2 mb-4">
  <div className="w-3 h-3 rounded-full bg-green-500"></div>

  <p className="font-semibold text-purple-700">
    Generated by Gemini AI
  </p>
</div>

      {plan && (
        <div className="mt-6 bg-purple-50 p-5 rounded-2xl whitespace-pre-wrap">
          {plan}
        </div>
      )}
    </div>
  );
}